### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: invalid transaction: Missing inputs. Code:-25

### ISSUE THREAD

**Issue by cloudwheels** [dashpay/platform#136]
## Expected Behavior

Spend funds from an account with a balance

## Current Behavior

Get error as per title

## Possible Solution

Investigate generated transaction inputs / script

## Steps to Reproduce (for bugs)

```
const Dash = require('dash');

const clientOpts = {
    network: 'evonet',
    wallet: {
        mnemonic: "wrist ladder salute build walk other scrap stumble true hotel layer treat"
    }
};




async function sendFunds(amount, toAddress) {
    try {

        const client = new Dash.Client(clientOpts);
        const account = await client.wallet.getAccount();
        console.log(`retrieved account`)
        const accBalTotal = account.getTotalBalance();
        const accBalUnconf = account.getUnconfirmedBalance()
        const accBalConf = account.getConfirmedBalance()
        console.log(`Total balance: ${accBalTotal}`)
        console.log(`Unconfirmed balance: ${accBalUnconf}`)
        console.log(`Confirmed balance: ${accBalConf}`)
        const transaction = account.createTransaction({
            recipients: [
                {
                    recipient: toAddress,
                    satoshis: amount
                }
            ]
        });
        const result = await account.broadcastTransaction(transaction);
        console.log('Transaction broadcast!\nTransaction ID:', result);

        return;
    } catch (e) {
        throw e;
    }


}

(async () => {
    await sendFunds(1000000, 'yMAaR92yKhK7hcKbNGNvAwjRQngx2UR8et')
})()
```

```
warn: Running on a NodeJS env without any specified adapter. Data will not persist.
retrieved account
Total balance: 56514754820
Unconfirmed balance: 0
Confirmed balance: 56514754820
(node:243071) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: invalid transaction: Missing inputs. Code:-25
    at Object.exports.createStatusError (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/client_interceptors.js:618:8)
    at InterceptingListener._callNext (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/client_interceptors.js:574:12)
    at InterceptingListener.onReceiveStatus (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/nigel/Dev/autofaucet-express/node_modules/grpc/src/client_interceptors.js:847:24)
(node:243071) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:243071) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Your Environment
nodejs 12.16.2
dash@3.14.1

**Comment by markin-io** [comment]
@dashameter hey! Apologies for the late response. Just finished checking out these:
https://github.com/dashameter/dash-dapp-autofaucet/blob/master/sendTx1.js
https://github.com/dashameter/dash-dapp-autofaucet/blob/master/sendTx2.js

I managed to reproduce the `Merkle diff` error a couple of times, but it does not happen all the time. 
However, both mnemonics produce `Missing inputs` or `Transaction already in chain` errors every time I run the scripts.

Those are "heavy" wallets with around 500 transactions, so I assume some of them are not making it to the wallet store, and hence we have incorrect UTXO selection. 

So, no matter what DAPI addresses are chosen, it will still be the same. Please, discard my original assumption about the node being out of sync. 

We are continuing to narrow down this problem. In the meantime, I'd suggest using a fresh wallet, because, from my current experience, I see problems start appearing if the wallet has more than 300 transactions in it.

**Comment by dash-maverick** [comment]
There is even a know workaround connected to the state of having > 300 transactions

**Comment by dashameter** [comment]
> There is even a know workaround connected to the state of having > 300 transactions

@dash-maverick can you share the known workaround ?

**Comment by dash-maverick** [comment]
> 

I made a mistake in my previous comment and fixed that right now with a bit of more explanation

**Comment by dashameter** [comment]
waiting for testnet to be online for retest
