### ISSUE TITLE
`yarn install` fails on node v20

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#1531]
0. Clone repo
   ```sh
   git clone --depth=1 git@github.com:dashpay/platform.git ./dashpay-platform/
   pushd ./dashpay-platform/
   ```
1. Install deps onto Ubuntu 22.04 LTS
   ```sh
   sudo apt install -y \
       build-essential \
       clang \
       cmake \
       g++ \
       gcc \
       libgmp-dev \
       libpython3.10-dev \
       libssl-dev \
       libzmq3-dev \
       pkg-config
   ```
   ```sh
   apt install -y \
       protobuf-compiler
   ```
2. Install node@18
   ```sh
   curl https://webi.sh/node@20 | sh
   source ~/.config/envman/PATH.env
   ```
3. Install platform
   ```sh
   corepack enable
   yarn install
   ```
4. Experience the pain and sadness of the empty void...

```text
# This file contains the result of Yarn building a package (protobufjs@npm:6.11.4)
# Script name: postinstall


node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [Error]: [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///mnt/dashstore/app/dashpay-platform/.yarn/unplugged/protobufjs-npm-6.11.4-af11968b80/node_modules/protobufjs/package.json" needs an import assertion of type "json"
    at load$1 (file:///mnt/dashstore/app/dashpay-platform/.pnp.loader.mjs:1458:17)
    at nextLoad (node:internal/modules/esm/hooks:833:28)
    at Hooks.load (node:internal/modules/esm/hooks:416:26)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.<anonymous> (node:internal/modules/esm/worker:136:5)
    at process.emit (node:events:514:28)
    at process.emit (/mnt/dashstore/app/dashpay-platform/.pnp.cjs:28770:25) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}

Node.js v20.9.0
```

**Comment by pshenmic** [comment]
I can see the same message on the node v18 on the fresh ubuntu instance, will be investigating

**Comment by coolaj86** [comment]
Interesting, because once I switched node versions and reran it, it worked.

**Comment by coolaj86** [comment]
I believe a new point release of v18 just came out, so it could be an npm-hosted static build (maybe the json `protoc`) that hasn't yet been republished.

**Comment by pshenmic** [comment]
https://github.com/dashpay/platform/pull/1562
