### ISSUE TITLE
bug(dashmate) : DAPI API service constantly restarting, Wasm SIMD unsupported   

### ISSUE THREAD

**Issue by qwizzie** [dashpay/platform#2033]
dashmate status services 

![Knipsel](https://github.com/user-attachments/assets/4ed3d26b-0dd8-4361-be4c-0d9edf0a0502)

Checked together with pshenmic my docker logs of container DAPI API : 

ERROR (35): CompileError: WebAssembly.Module(): Compiling function #1534:"bytecount::simd::wasm::chunk_num_chars::h5a3553..." failed: Wasm SIMD unsupported @+3063056
    at Object.initSync (/platform/packages/wasm-dpp/dist/wasm/wasm_dpp.js:2425:46061)
    at /platform/packages/wasm-dpp/dist/index.js:71:20
    at Generator.next (<anonymous>)
    at /platform/packages/wasm-dpp/dist/index.js:30:71
    at new Promise (<anonymous>)
    at __awaiter (/platform/packages/wasm-dpp/dist/index.js:26:12)
    at loadDppModule (/platform/packages/wasm-dpp/dist/index.js:62:29)
    at /platform/packages/wasm-dpp/dist/index.js:52:30
    at Generator.next (<anonymous>)
    at /platform/packages/wasm-dpp/dist/index.js:30:71

See : 

https://github.com/dashpay/platform/pull/1607
https://github.com/dashpay/platform/issues/1583

## Expected Behavior
DAPI API serice running
I also expected wasm-dpp to not form an issue anymore, after it was removed as dependency late 2023 (see 1607)

## Current Behavior
DAPI API service constantly restarting, filling my docker logs of DAPI API service with above mentioned error text related to wasm-dpp

## Possible Solution
Remove wasp-dpp as dependency again with regards to DAPI API and check it does not linger anywhere else

## Steps to Reproduce (for bugs)
pshenmic has reproduced this specific hardware-related bug with me before late 2023 (see 1583). 
He provided me back then with a sample application to reproduce my case

![Knipsel](https://github.com/user-attachments/assets/6394ffd6-4221-4640-911b-0e5963ccc5d5)
![Knipsel1](https://github.com/user-attachments/assets/cd42389c-0624-4cb3-a949-2400945134cc)

## Context
This bug prevents me (and other Evonode operators with similar hardware setup) a successful running of all Platform services. I consider this a high priority bug that needs solving as soon as possible.  

## Your Environment
Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-190-generic x86_64)
Dashmate : 1.0.2 (dashmate reset --config mainnet --hard, download from scratch, landed on 1.0.1 and later updated to v1.0.2) 
Node.js : 20.10.0

Specific hardware 

Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      44 bits physical, 48 bits virtual
CPU(s):                             8
On-line CPU(s) list:                0-7
Thread(s) per core:                 1
Core(s) per socket:                 8
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
Stepping:                           4
CPU MHz:                            2992.970
BogoMIPS:                           5985.94
Hypervisor vendor:                  Microsoft
Virtualization type:                full
L1d cache:                          256 KiB
L1i cache:                          256 KiB
L2 cache:                           8 MiB
L3 cache:                           198 MiB
NUMA node0 CPU(s):                  0-7

**Comment by qwizzie** [comment]
I decided to move to a different VPS with a different CPU (Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz), different OS (Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-117-generic x86_64) and with a different node.js version (v20.16.0). Mainly because of costs.

Problem solved, all services are running under dashmate status services.
Let me know if i can now close this ticket or if you need it to stay open.
