### ISSUE TITLE
Overflow error on testnet

### ISSUE THREAD

**Issue by shumkov** [dashpay/platform#2311]
```
2024-11-04T04:10:53.581242Z  INFO drive_abci::abci::handler::process_proposal: Processed proposal with 0 transactions for height: 988, round: 0 in 80 ms, invalid_tx_count: 0, valid_tx_count: 0, elapsed_time_ms: 80, storage_fees: 0, processing_fees: 0
    at packages/rs-drive-abci/src/abci/handler/process_proposal.rs:323 on main ThreadId(1)
    in tenderdash_abci::tracing_span::abci with endpoint: "ProcessProposal", request_id: "2fdcb3bb-bea4-4c0f-b459-f60f729266f7", height: 988, round: 0

ERROR drive_abci: panic, panic: panicked at packages/rs-dpp/src/data_contract/document_type/property/mod.rs:210:36:
attempt to multiply with overflow
```

syncing testnet with debug

**Comment by thepastaclaw** [comment]
Closing as stale — this testnet overflow error was reported against an old platform version (Nov 2024). Multiple releases have shipped since. If the issue persists on current testnet, please reopen with updated details.
