### ISSUE TITLE
dashmate: yarn needs to be set to `berry` system wide

### ISSUE THREAD

**Issue by dashameter** [dashpay/platform#397]
Yarn version for dashmate needs to be modern (berry) but it's not set project specific and changes the yarn version for the entire host system. (Discussed with @markin-io  on weekly qa call)

yarn version should be set project specific

**Comment by dashameter** [comment]
on platform .12 running

`yarn install && yarn setup` throws:

```
(node:1618279) TypeError Plugin: dashmate: Cannot read properties of undefined (reading 'dash')
module: @oclif/core@1.3.4
task: toCached
plugin: dashmate
root: platform/packages/dashmate
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1618279) TypeError Plugin: dashmate: Cannot read properties of undefined (reading 'dash')
module: @oclif/core@1.3.4
task: toCached
plugin: dash
```


`yarn setup`

```
Internal Error: @dashevo/platform@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at nF.resolve (.yarn/releases/yarn-3.2.1.cjs:438:4808)
    at Bd.resolve (.yarn/releases/yarn-3.2.1.cjs:396:1454)
    at .yarn/releases/yarn-3.2.1.cjs:442:6403
    at Rg (.yarn/releases/yarn-3.2.1.cjs:395:11098)
    at ee (.yarn/releases/yarn-3.2.1.cjs:442:6383)
    at .yarn/releases/yarn-3.2.1.cjs:442:7231
```
I have to run `yarn install` first before running `yarn setup` even though `yarn setup` is running `yarn install` as well


`yarn set version 3.1.0` throws the same `yarn setup` error as shown above

**Comment by pshenmic** [comment]
Fixed ages ago as I remember

**Comment by shumkov** [comment]
Agree
