### ISSUE TITLE
Connecting to local group nodes throws ServerError: DAPI JSON RPC wrong http code: Service Unavailable

### ISSUE THREAD

**Issue by mayoreee** [dashpay/platform#455]
Connecting to local group nodes throws `ServerError: DAPI JSON RPC wrong http code: Service Unavailable`
## Expected Behavior

Successfully connect to local dashmate
## Current Behavior

```
Something went wrong:
 NoAvailableAddressesForRetryError: No available addresses for retry: DAPI JSON RPC wrong http code: Service Unavailable
    at JsonRpcTransport.request (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/JsonRpcTransport/JsonRpcTransport.js:101:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async connect (/Volumes/harddrive/Projects/sandbox/send.js:11:10) {
  code: 503,
  data: {},
  dapiAddress: DAPIAddress {
    host: '127.0.0.1',
    httpPort: 3000,
    grpcPort: 3010,
    proRegTxHash: undefined,
    banCount: 1,
    banStartTime: 1656666430828
  },
  cause: ServerError: DAPI JSON RPC wrong http code: Service Unavailable
      at JsonRpcTransport.createJsonTransportError (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/JsonRpcTransport/createJsonTransportError.js:15:12)
      at JsonRpcTransport.request (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/JsonRpcTransport/JsonRpcTransport.js:89:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async connect (/Volumes/harddrive/Projects/sandbox/send.js:11:10) {
    code: 503,
    data: {},
    dapiAddress: DAPIAddress {
      host: '127.0.0.1',
      httpPort: 3000,
      grpcPort: 3010,
      proRegTxHash: undefined,
      banCount: 1,
      banStartTime: 1656666430828
    }
  }
}
```

Docker containers running:
```
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS              PORTS                                                                                  NAMES
973a8dbf7f05   envoyproxy/envoy:v1.16-latest   "/docker-entrypoint.…"   6 minutes ago   Up 6 minutes        0.0.0.0:3100->10000/tcp, 0.0.0.0:3110->50051/tcp                                       dash_masternode_local_2_dapi_envoy_1
2cd8296366b9   envoyproxy/envoy:v1.16-latest   "/docker-entrypoint.…"   6 minutes ago   Up 6 minutes        0.0.0.0:3200->10000/tcp, 0.0.0.0:3210->50051/tcp                                       dash_masternode_local_3_dapi_envoy_1
6591c645695e   envoyproxy/envoy:v1.16-latest   "/docker-entrypoint.…"   6 minutes ago   Up 6 minutes        0.0.0.0:3000->10000/tcp, 0.0.0.0:3010->50051/tcp                                       dash_masternode_local_1_dapi_envoy_1
51e9253066d0   dashpay/dapi:0.22               "docker-entrypoint.s…"   6 minutes ago   Up 3 minutes        2500-2501/tcp, 2510/tcp                                                                dash_masternode_local_3_dapi_api_1
777e6cd6bb2b   dashpay/dapi:0.22               "docker-entrypoint.s…"   6 minutes ago   Up 3 minutes        2500-2501/tcp, 2510/tcp                                                                dash_masternode_local_2_dapi_api_1
e701a7819233   dashpay/dapi:0.22               "docker-entrypoint.s…"   6 minutes ago   Up About a minute   2500-2501/tcp, 2510/tcp                                                                dash_masternode_local_1_dapi_api_1
ced669ed0bfb   dashpay/tenderdash:0.7          "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes        0.0.0.0:26656->26656/tcp, 127.0.0.1:26657->26657/tcp, 26660/tcp                        dash_masternode_local_1_drive_tenderdash_1
05c416ab5994   dashpay/tenderdash:0.7          "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes        26656-26657/tcp, 26660/tcp, 0.0.0.0:26756->26756/tcp, 127.0.0.1:26757->26757/tcp       dash_masternode_local_2_drive_tenderdash_1
1a78b313ef29   dashpay/tenderdash:0.7          "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes        26656-26657/tcp, 26660/tcp, 0.0.0.0:26856->26856/tcp, 127.0.0.1:26857->26857/tcp       dash_masternode_local_3_drive_tenderdash_1
5f4611b464bd   dashpay/drive:0.22              "docker-entrypoint.s…"   6 minutes ago   Up 2 minutes        26658/tcp                                                                              dash_masternode_local_1_drive_abci_1
574f8e480c1a   dashpay/drive:0.22              "docker-entrypoint.s…"   6 minutes ago   Up 2 minutes        26658/tcp                                                                              dash_masternode_local_3_drive_abci_1
b0e12c30a0c5   dashpay/drive:0.22              "docker-entrypoint.s…"   6 minutes ago   Up About a minute   26658/tcp                                                                              dash_masternode_local_2_drive_abci_1
1d1938d1c27b   dashpay/dapi:0.22               "docker-entrypoint.s…"   4 days ago      Up 16 seconds       2500-2501/tcp, 2510/tcp                                                                dash_masternode_local_2_dapi_tx_filter_stream_1
9da0c4d73c34   dashpay/sentinel:1.6.0          "/bin/sh -c /run.sh"     4 days ago      Up 6 minutes                                                                                               dash_masternode_local_2_sentinel_1
4c2ed558f3d1   dashpay/dapi:0.22               "docker-entrypoint.s…"   4 days ago      Up About a minute   2500-2501/tcp, 2510/tcp                                                                dash_masternode_local_1_dapi_tx_filter_stream_1
3d0e6874ec31   dashpay/dapi:0.22               "docker-entrypoint.s…"   4 days ago      Up 32 seconds       2500-2501/tcp, 2510/tcp                                                                dash_masternode_local_3_dapi_tx_filter_stream_1
9fc473708dde   dashpay/sentinel:1.6.0          "/bin/sh -c /run.sh"     4 days ago      Up 6 minutes                                                                                               dash_masternode_local_3_sentinel_1
a92e26ce6b35   dashpay/sentinel:1.6.0          "/bin/sh -c /run.sh"     4 days ago      Up 6 minutes                                                                                               dash_masternode_local_1_sentinel_1
16bd7eacaf2e   dashpay/dashd:18.0.0-rc5        "/docker-entrypoint.…"   4 days ago      Up 6 minutes        9998-9999/tcp, 19998-19999/tcp, 0.0.0.0:20101->20101/tcp, 127.0.0.1:20102->20102/tcp   dash_masternode_local_2_core_1
0780fdaddba4   dashpay/dashd:18.0.0-rc5        "/docker-entrypoint.…"   4 days ago      Up 6 minutes        9998-9999/tcp, 19998-19999/tcp, 0.0.0.0:20201->20201/tcp, 127.0.0.1:20202->20202/tcp   dash_masternode_local_3_core_1
b12a0d2d17cb   dashpay/dashd:18.0.0-rc5        "/docker-entrypoint.…"   4 days ago      Up 6 minutes        9998-9999/tcp, 19998-19999/tcp, 0.0.0.0:20001->20001/tcp, 127.0.0.1:20002->20002/tcp   dash_masternode_local_1_core_1
e5f5a1e31df9   dashpay/dashd:18.0.0-rc5        "/docker-entrypoint.…"   4 days ago      Up 6 minutes        9998-9999/tcp, 19998-19999/tcp, 0.0.0.0:20301->20301/tcp, 127.0.0.1:20302->20302/tcp   dash_masternode_local_seed_core_1
```

Logs in `dashpay/tenderdash:0.7` container:
```
E[2022-06-25|10:13:11.697] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:14.747] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:20.481] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:23.524] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:26.555] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:33.396] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:36.444] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
E[2022-06-25|10:13:39.496] abci.socketClient failed to connect to tcp://drive_abci:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 172.24.3.5:26658: connect: connection refused"
```

Logs in `dashpay/sentinel:1.6.0` container:
```
sentinel/lib/base58.py:119: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert get_bcaddress_version('15VjRaDX9zpbA8LVnbrCAFzrVzN7ixHNsC') is 0
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
Terminated
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
dashd not synced with network! Awaiting full sync before running Sentinel.
```

**Note: `dapi_api` and `tx_filter` containers keep dying and restarting:**

<img width="1017" alt="Screenshot 2022-07-01 at 10 28 30" src="https://user-images.githubusercontent.com/15247893/176880415-b16766d5-40dc-4fdc-955b-d63827fbe540.png">

`dapi_api` containers logs in `local_1`, `local_2` and `local_3` nodes:
<img width="1027" alt="Screenshot 2022-07-01 at 10 41 22" src="https://user-images.githubusercontent.com/15247893/176879469-2817b071-eb7e-4c25-a3e1-2d8bafa8d0eb.png">

`tx_filter` containers logs in `local_1`, `local_2` and `local_3` nodes:
<img width="1009" alt="Screenshot 2022-07-01 at 10 43 58" src="https://user-images.githubusercontent.com/15247893/176879570-242a2334-f2af-4b69-a486-569bf6e547ff.png">

## Steps to Reproduce (for bugs)

```js
const Dash = require('dash');

const client = new Dash.Client({
  network: 'regtest',
  seeds: [{
    host: '127.0.0.1',
    httpPort: 3000,
    grpcPort: 3010
  }],
});

async function connect() {
  return await client.getDAPIClient().core.getBestBlockHash();
}

connect()
  .then((d) => console.log('Connected. Best block hash:\n', d))
  .catch((e) => console.error('Something went wrong:\n', e))
  .finally(() => client.disconnect());
```

## Your Environment

* Version used: `dashmate v0.22.13`
* Environment name and version: `node-v16.15.1`, `docker v20.10.12`
* Operating System and version (desktop, server, or mobile): `darwin-arm64`, `M1 Mac`

**Comment by mayoreee** [comment]
Temporary workaround based on recommendations by the DCG team:

```
docker rm -fv $(docker ps -aq)
docker volume rm $(docker volume ls -q) 
rm -r ~/.dashmate
git clone --branch master --single-branch https://github.com/dashevo/platform.git
cd platform
npm run setup 
dashmate config set --config=local platform.sourcePath “/absolute/path/to/platform”
dashmate group:start
```

**Additional Info:** This issue is expected to be fixed in Platform v0.23 release.

**Comment by SamKirby22** [comment]
@shumkov do we still need extra detail from @mayoreee on this?

**Comment by shumkov** [comment]
Core is not started yet so there are two options:
1. Nodes are syncing and you need to wait little bit
2. There are some errors

We need logs from dashd containers to figure this out

**Comment by SamKirby22** [comment]
@mayoreee are these things you can provide?

**Comment by shumkov** [comment]
No details were provided. I think this issue is not actual anymore
