### ISSUE TITLE
bug(dashmate): local nodes fails to start after dashmate reset

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#785]
## Expected Behavior

Local nodes should start successfully after reset operation

## Current Behavior

Nodes fails to start due to missing environment variables that are not set up during `dashmate group reset`

## Steps to Reproduce (for bugs)

1. dashmate setup local
2. dashmate group reset
3. dashmate group start

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by pshenmic** [comment]
https://github.com/dashpay/platform/issues/99

**Comment by pshenmic** [comment]
The error pops in the every drive_abci container:
```
/platform/.yarn/cache/dotenv-safe-npm-8.2.0-f1bcdebce9-8b73770330.zip/node_modules/dotenv-safe/index.js:31
            throw new MissingEnvVarsError(allowEmptyValues, options.path || '.env', example, missing, dotenvResult.error);
                  ^
MissingEnvVarsError: The following variables were defined in .env.example but are not present in the environment:
  DPNS_MASTER_PUBLIC_KEY, DPNS_SECOND_PUBLIC_KEY, DASHPAY_MASTER_PUBLIC_KEY, DASHPAY_SECOND_PUBLIC_KEY, FEATURE_FLAGS_MASTER_PUBLIC_KEY, FEATURE_FLAGS_SECOND_PUBLIC_KEY, MASTERNODE_REWARD_SHARES_MASTER_PUBLIC_KEY, MASTERNODE_REWARD_SHARES_SECOND_PUBLIC_KEY
Make sure to add them to .env or directly to the environment.

If you expect any of these variables to be empty, you can use the allowEmptyValues option:
require('dotenv-safe').config({
  allowEmptyValues: true
});
    at Object.config (/platform/.yarn/cache/dotenv-safe-npm-8.2.0-f1bcdebce9-8b73770330.zip/node_modules/dotenv-safe/index.js:31:19)
    at Object.<anonymous> (/platform/packages/js-drive/scripts/abci.js:1:49)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require$$0.Module._extensions..js (/platform/.pnp.cjs:11822:33)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.require$$0.Module._load (/platform/.pnp.cjs:11645:22)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0) {
  missing: [
    'DPNS_MASTER_PUBLIC_KEY',
    'DPNS_SECOND_PUBLIC_KEY',
    'DASHPAY_MASTER_PUBLIC_KEY',
    'DASHPAY_SECOND_PUBLIC_KEY',
    'FEATURE_FLAGS_MASTER_PUBLIC_KEY',
    'FEATURE_FLAGS_SECOND_PUBLIC_KEY',
    'MASTERNODE_REWARD_SHARES_MASTER_PUBLIC_KEY',
    'MASTERNODE_REWARD_SHARES_SECOND_PUBLIC_KEY'
  ],
  sample: '.env.example',
  example: '.env.example'
}
```

**Comment by pshenmic** [comment]
Fixed in https://github.com/dashpay/platform/pull/991
