### ISSUE TITLE
Error: `Invalid instant lock proof signature` when creating new Identity  

### ISSUE THREAD

**Issue by AhmedElwerdany** [dashpay/platform#791]
## Expected Behavior
I Expect it to create new Identity 

## Current Behavior
` Error: Invalid instant lock proof signature`

## Steps to Reproduce (for bugs)

1.
```javascript
const clientOpts = {
  network: 'local',
  wallet: {
    // Funded with `dashmate`
    mnemonic: `expose symbol airport gate because pottery hope become congress empower foot measure`,
  }
};

const client = new Client(clientOpts);
```
2.
```javascript
export function createIdentity() {
  const identity = client.platform.identities.register();
  return identity;
}

```
3.
```javascript
 createIdentity()
        .then(d => console.log('Identity:\n', d.toJSON()))
        .catch(e => console.error('Something went wrong:\n', e));
```
4.
![image](https://user-images.githubusercontent.com/9258083/219977308-9d029e1e-2f7a-4399-82b3-c8193ea07e75.png)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by pshenmic** [comment]
As far as I remember, Invalid instant lock proof signature means that you don't have platform blocks propogating. It either just have not started yet (you gotta wait few minutes after successful group start), or something bad happened in the local setup. You can check `drive_abci` container logs for more info. In successful case you should see blocks producing and coming in the logs.

**Comment by AhmedElwerdany** [comment]
`dash_masternode_local_3-drive_abci-1`
```
2023-02-19 22:39:35 [2023-02-19 20:39:35.412 +0000] INFO (35 on 863feff43f94): Block commit #83 with appHash E6A0E4ABB2CD1AF51B7EACDE4886EFDE595EF298BC5877AB8FD0A01426E4B671
2023-02-19 22:39:35     appHash: "E6A0E4ABB2CD1AF51B7EACDE4886EFDE595EF298BC5877AB8FD0A01426E4B671"
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "commit"
2023-02-19 22:42:36 [2023-02-19 20:42:36.838 +0000] INFO (35 on 863feff43f94): Masternode identities are synced for heights from 1113 to 1114: 0 created, 0 updated, 0 removed
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "beginBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.838 +0000] INFO (35 on 863feff43f94): Block begin #84
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "beginBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.948 +0000] INFO (35 on 863feff43f94): Block end #84 (valid txs = 0, invalid txs = 0)
2023-02-19 22:42:36     validTxCount: 0
2023-02-19 22:42:36     invalidTxCount: 0
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "endBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.952 +0000] INFO (35 on 863feff43f94): Block commit #84 with appHash 882037CD4A4BCD088D876775AD46D75F65FB0C37D6488AB686356007E096B23B
2023-02-19 22:42:36     appHash: "882037CD4A4BCD088D876775AD46D75F65FB0C37D6488AB686356007E096B23B"
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "commit"
```

``dash_masternode_local_1-drive_abci-1``
```
2023-02-19 22:36:33 [2023-02-19 20:36:33.932 +0000] INFO (35 on 395439a78db2): Block commit #82 with appHash 872508F332B8454471F60A73DDE3110CE3F0DCBFA66EAA4DD88A36206DC044C7
2023-02-19 22:36:33     appHash: "872508F332B8454471F60A73DDE3110CE3F0DCBFA66EAA4DD88A36206DC044C7"
2023-02-19 22:36:33     driveVersion: "0.23.0"
2023-02-19 22:36:33     height: "82"
2023-02-19 22:36:33     abciMethod: "commit"
2023-02-19 22:39:35 [2023-02-19 20:39:35.257 +0000] INFO (35 on 395439a78db2): Masternode identities are synced for heights from 1112 to 1113: 0 created, 0 updated, 0 removed
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "beginBlock"
2023-02-19 22:39:35 [2023-02-19 20:39:35.257 +0000] INFO (35 on 395439a78db2): Block begin #83
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "beginBlock"
2023-02-19 22:39:35 [2023-02-19 20:39:35.319 +0000] INFO (35 on 395439a78db2): Block end #83 (valid txs = 0, invalid txs = 0)
2023-02-19 22:39:35     validTxCount: 0
2023-02-19 22:39:35     invalidTxCount: 0
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "endBlock"
2023-02-19 22:39:35 [2023-02-19 20:39:35.322 +0000] INFO (35 on 395439a78db2): Block commit #83 with appHash E6A0E4ABB2CD1AF51B7EACDE4886EFDE595EF298BC5877AB8FD0A01426E4B671
2023-02-19 22:39:35     appHash: "E6A0E4ABB2CD1AF51B7EACDE4886EFDE595EF298BC5877AB8FD0A01426E4B671"
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "commit"
2023-02-19 22:42:36 [2023-02-19 20:42:36.807 +0000] INFO (35 on 395439a78db2): Masternode identities are synced for heights from 1113 to 1114: 0 created, 0 updated, 0 removed
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "beginBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.808 +0000] INFO (35 on 395439a78db2): Block begin #84
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "beginBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.881 +0000] INFO (35 on 395439a78db2): Block end #84 (valid txs = 0, invalid txs = 0)
2023-02-19 22:42:36     validTxCount: 0
2023-02-19 22:42:36     invalidTxCount: 0
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "endBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.884 +0000] INFO (35 on 395439a78db2): Block commit #84 with appHash 882037CD4A4BCD088D876775AD46D75F65FB0C37D6488AB686356007E096B23B
2023-02-19 22:42:36     appHash: "882037CD4A4BCD088D876775AD46D75F65FB0C37D6488AB686356007E096B23B"
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "commit"
```

`dash_masternode_local_2-drive_abci-1`
```
2023-02-19 22:36:33 [2023-02-19 20:36:33.889 +0000] INFO (35 on cf8b575f94dd): Block commit #82 with appHash 872508F332B8454471F60A73DDE3110CE3F0DCBFA66EAA4DD88A36206DC044C7
2023-02-19 22:36:33     appHash: "872508F332B8454471F60A73DDE3110CE3F0DCBFA66EAA4DD88A36206DC044C7"
2023-02-19 22:36:33     driveVersion: "0.23.0"
2023-02-19 22:36:33     height: "82"
2023-02-19 22:36:33     abciMethod: "commit"
2023-02-19 22:39:35 [2023-02-19 20:39:35.364 +0000] INFO (35 on cf8b575f94dd): Masternode identities are synced for heights from 1112 to 1113: 0 created, 0 updated, 0 removed
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "beginBlock"
2023-02-19 22:39:35 [2023-02-19 20:39:35.364 +0000] INFO (35 on cf8b575f94dd): Block begin #83
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "beginBlock"
2023-02-19 22:39:35 [2023-02-19 20:39:35.435 +0000] INFO (35 on cf8b575f94dd): Block end #83 (valid txs = 0, invalid txs = 0)
2023-02-19 22:39:35     validTxCount: 0
2023-02-19 22:39:35     invalidTxCount: 0
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "endBlock"
2023-02-19 22:39:35 [2023-02-19 20:39:35.483 +0000] INFO (35 on cf8b575f94dd): Block commit #83 with appHash E6A0E4ABB2CD1AF51B7EACDE4886EFDE595EF298BC5877AB8FD0A01426E4B671
2023-02-19 22:39:35     appHash: "E6A0E4ABB2CD1AF51B7EACDE4886EFDE595EF298BC5877AB8FD0A01426E4B671"
2023-02-19 22:39:35     driveVersion: "0.23.0"
2023-02-19 22:39:35     height: "83"
2023-02-19 22:39:35     abciMethod: "commit"
2023-02-19 22:42:36 [2023-02-19 20:42:36.816 +0000] INFO (35 on cf8b575f94dd): Masternode identities are synced for heights from 1113 to 1114: 0 created, 0 updated, 0 removed
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "beginBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.816 +0000] INFO (35 on cf8b575f94dd): Block begin #84
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "beginBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.865 +0000] INFO (35 on cf8b575f94dd): Block end #84 (valid txs = 0, invalid txs = 0)
2023-02-19 22:42:36     validTxCount: 0
2023-02-19 22:42:36     invalidTxCount: 0
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "endBlock"
2023-02-19 22:42:36 [2023-02-19 20:42:36.883 +0000] INFO (35 on cf8b575f94dd): Block commit #84 with appHash 882037CD4A4BCD088D876775AD46D75F65FB0C37D6488AB686356007E096B23B
2023-02-19 22:42:36     appHash: "882037CD4A4BCD088D876775AD46D75F65FB0C37D6488AB686356007E096B23B"
2023-02-19 22:42:36     driveVersion: "0.23.0"
2023-02-19 22:42:36     height: "84"
2023-02-19 22:42:36     abciMethod: "commit"
```

**Comment by pshenmic** [comment]
hmmm, seems quite okay 🤔🤔
Looks like blocks are there, might be something with the local setup. I would like to ask you to completely reset the network and try again, but unfortunately dashmate group reset command is not working right now :( (#785). 

As a workaround, you can use this script to purge all local dashmate data and settings:
```
docker stop $(docker ps -q)
docker system prune -f
docker volume prune -f
rm -rf ~/.dashmate
```
It will drop all the containers on your system so use with caution if you have any other docker stuff on your system.
After that, just do all setup and start stuff again :)


At the same time, I tried to reproduce your error and it looks like this invalid proof is not hitting me, but I got another error instead, that I think related to the SDK. Looks like Identity is gettimg registered but instantly fails when SDK tries to return it to user.

```
TypeError: responseMetadata.getTimeMs is not a function
    at Platform.<anonymous> (/Users/pshenmic/WebstormProjects/platform/packages/js-dash-sdk/build/src/SDK/Client/Platform/methods/identities/get.js:84:54)
    at step (/Users/pshenmic/WebstormProjects/platform/packages/js-dash-sdk/build/src/SDK/Client/Platform/methods/identities/get.js:33:23)
    at Object.next (/Users/pshenmic/WebstormProjects/platform/packages/js-dash-sdk/build/src/SDK/Client/Platform/methods/identities/get.js:14:53)
    at fulfilled (/Users/pshenmic/WebstormProjects/platform/packages/js-dash-sdk/build/src/SDK/Client/Platform/methods/identities/get.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Just reported to the team, will get back here once I get the answers 🫶

**Comment by pshenmic** [comment]
Actually, I just forgot to rebuild the SDK when switched the branch, so my issue is gone and I was able to register an identity. Let me know if you still have issues with it

**Comment by AhmedElwerdany** [comment]
resetting the network solved the issue. thank you !
